build-all:
	mkdir -p build
	cd build && cmake .. && make

build-analyzer:
	mkdir -p build
	cd build && cmake .. && make analyzer

run-analyzer:
	cd build && ./analyzer

build-server:
	mkdir -p build
	cd build && cmake .. && make server

run-server:
	cd build && ./server

build-client:
	mkdir -p build
	cd build && cmake .. && make client

run-client:
	cd build && ./client